### ISSUE TITLE
feat: each user should have a unique username 

### ISSUE THREAD

**Issue by MahendraDani** [MahendraDani/trails#2]
## Description
Currently, all users new and existing can directly login into the app using their Github account. And `user` table doesn't have any `username` attribute.

## TODO
- [ ] Alter the prisma schema and add the attribute `username` with datatype `String` Varchar(255) of defined length.
- [ ] Create a new page, where new user can first create a new `username` for themselves and then redirect them to the `dashboard`
- [ ] For existing users they should directly login into their account and should be redirected to their respective dashboard.
